language: go

go:
    - "1.7.1"

env:
    global:
        - SSH_KEY="id_rsa"
        - GIT_NAME="Ruochen Jiang"
        - GIT_EMAIL="ruochenj@sfu.ca"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="source"

before_install:
    - openssl aes-256-cbc -K $encrypted_7123cbeebab3_key -iv $encrypted_7123cbeebab3_iv -in id_rsa.enc -out id_rsa -d

before_script:
    - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
    - go get -u -v github.com/spf13/hugo

script:
    - git clone https://github.com/rcoedo/hugo-steam-theme ./themes/hugo-steam-theme
    - hugo

after_success:
    - ./deploy.sh
