language: go

go:
    - "1.7.1"

env:
    global:
        - SSH_KEY="id_rsa"
        - GIT_NAME="Ruochen Jiang"
        - GIT_EMAIL="ruochenj@sfu.ca"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="source"


install:
    - go get -u github.com/spf13/hugo
    - go install github.com/spf13/hugo

script:
    - hugo

after_success:
    - ./deploy.sh
